### ISSUE TITLE
monkeypatch pushState/replaceState so that we can trigger snapshot on push of new state

### ISSUE THREAD

**Issue by capaj** [capaj/mobx-location#1]
currenlty if a new URL is pushed via history.pushstate we don't make a new snapshot because it doesn't trigger `popstate` event

**Comment by developer-lindner** [comment]
@capaj Any news here?

**Comment by capaj** [comment]
sorry didn't had time yet. I will try to pick it up this weekend.

**Comment by capaj** [comment]
@developer-lindner finally published as 0.3.0
